quarkus:
  rest-client:
    logging:
      scope: request-response
  log:
    category:
      "org.jboss.resteasy.reactive.client.logging":
        level: DEBUG
#      "org.jboss.resteasy.reactive.server.handlers.ParameterHandler":
#        level: DEBUG
#      "org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext":
#        level: DEBUG